// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwPPCvNbM6Q9x0tzwf__8xgMQbUVAU8tc',
    appId: '1:348852942889:web:768020344c972f1fa9c438',
    messagingSenderId: '348852942889',
    projectId: 'chat-99b56',
    authDomain: 'chat-99b56.firebaseapp.com',
    storageBucket: 'chat-99b56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIFLWXX3kJw6xOAyWK7ndYRdbO4LNgQw',
    appId: '1:348852942889:android:8de855bb0f203f13a9c438',
    messagingSenderId: '348852942889',
    projectId: 'chat-99b56',
    storageBucket: 'chat-99b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0FIJNzLOP1EMZobmm7fCPsPUSXcUp0k',
    appId: '1:348852942889:ios:ca0acdfee7ff299ba9c438',
    messagingSenderId: '348852942889',
    projectId: 'chat-99b56',
    storageBucket: 'chat-99b56.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0FIJNzLOP1EMZobmm7fCPsPUSXcUp0k',
    appId: '1:348852942889:ios:32b780fcbc409f65a9c438',
    messagingSenderId: '348852942889',
    projectId: 'chat-99b56',
    storageBucket: 'chat-99b56.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
